### ISSUE TITLE
MonoGame linking fails on Android

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#2981]
Creating a project that references MonoGame.Framework and MonoGame.Framework.Net fails to build the APK with the following error:

>5>	Adding obj\Debug\__library_projects__\MonoGame.Framework\native_library_imports\armeabi-v7a\libopenal32.so
5>	Adding obj\Debug\__library_projects__\MonoGame.Framework.Net\native_library_imports\armeabi-v7a\libopenal32.so
5>	Adding obj\Debug\__library_projects__\MonoGame.Framework\native_library_imports\armeabi\libopenal32.so
5>	Adding obj\Debug\__library_projects__\MonoGame.Framework.Net\native_library_imports\armeabi\libopenal32.so
5>	Adding obj\Debug\__library_projects__\MonoGame.Framework\native_library_imports\x86\libopenal32.so
5>	Adding obj\Debug\__library_projects__\MonoGame.Framework.Net\native_library_imports\x86\libopenal32.so
5>The "BuildApk" task failed unexpectedly.
5>System.ArgumentException: An item with the same key has already been added.

Here is a sample project, just put MonoGame next to it's root folder (App1):
https://mega.co.nz/#!wI0zAJJL!7xSM0vFbT1KW94wB9h3r7OeUZFk6dOSNsFFv-aMGo6I

**Comment by vostok4** [comment]
@tomspilman I have tested the change in #3246, and it seems to work, however it has some unintuitive behaviour. It builds two copies of MonoGame.Framework.dll:

    bin\MonoGame.Framework.Net\Android\AnyCPU\Release\MonoGame.Framework.dll
    bin\Android\AnyCPU\Release\MonoGame.Framework.dll

It seems to package successfully referencing either of the DLLs, so I guess it works, however is there a way to clean up the build output so that there aren't duplicates?

**Comment by tomspilman** [comment]
Yeah... my fix isn't a good one.  I just haven't had time to implement the right one.

**Comment by tgraupmann** [comment]
I had been manually removing one of the duplicate OpenAL native libraries.

Removing one of the duplicate sets of native libraries fixes the build/publish process:
obj\Debug\__library_projects__\MonoGame.Framework\native_library_imports\armeabi-v7a\libopenal32.so
obj\Debug\__library_projects__\MonoGame.Framework.Net\native_library_imports\armeabi-v7a\libopenal32.so

There can be only one! (queue the Highlander music)

**Comment by hach-que** [comment]
Does adding:

```
<Property Name="ProjectSpecificOutputFolder" Value="True" />
```

to the framework definition files not fix this issue?

**Comment by kjpou1** [comment]
@hach-que 

I have tested this and it is working fine.

**Comment by dellis1972** [comment]
@Nezz this should be fixed in the latest release of Xamarin.Android. Please re-open if not.

**Comment by tgraupmann** [comment]
This issue has been resolved in 3.4. You do however need to build with API 17 or better.

**Comment by kj4bix** [comment]
I'm still having the same problem described above. I'm trying to use CocosSharp which adds the MonoGame.Framework and MonoGame.Framework.Net - reading the above it seems it should be corrected, but I'm getting the same error:
"BuildApk" task failed unexpectedly. The exception is: "An item with the same key has already been added." I'm compiling for API level 23, is there some way to make this work?

Thanks

**Comment by totallyeviljake** [comment]
We fixed this in our fork of MonoGame by adding another project file for the .Net project and adding an AsstemblyInfo.cs file for the .Net project assembly. This is our fork: https://github.com/Cocos2DXNA/MonoGame/tree/develop there you will see a MonoGame.Framework.Net/AssemblyInfo.cs file. Once we did this we no longer had any problems with the BuildApk process in Xamarin Studio.

**Comment by dellis1972** [comment]
This will actually be fixed in the next release of Xamarin.Android :) Its a problem in the build system.

**Comment by vostok4** [comment]
FYI on the latest version of Xamarin.Android (tested on Xamarin.Android 6.0) this is no longer an issue, and the ProjectSpecificOutputFolder directive is no longer needed to be modified. We can finally package APKs  cleanly. Thanks to all involved!
