### ISSUE TITLE
[WinDX] Problem with shader textures/samplers and rendertarget swaps

### ISSUE THREAD

**Issue by pfferrao** [mono/MonoGame#3710]
Following in the issue #3700, this bug seems to affect all textures/samplers set by a shader, this example shows the problem using the stock DualTextureEffect:

```C#
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace DTBug {
    /// <summary>
    /// This is the main type for your game
    /// </summary>
    public class Game1 : Game {

        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;
        Texture2D texture_0, texture_1;
        RenderTarget2D rt;

        VertexBuffer v_buffer;
        DualTextureEffect dt_effect;

        public struct VertexDualTexture : IVertexType {

            Vector3 position;
            Vector2 tex1, tex2;

            public Vector3 Position { get { return position; } set { position = value; } }
            public Vector2 TextureCoordinate { get { return tex1; } set { tex1 = value; } }
            public Vector2 TextureCoordinate2 { get { return tex2; } set { tex2 = value; } }

            public readonly static VertexDeclaration dec = new VertexDeclaration
            (
                new VertexElement(0, VertexElementFormat.Vector3, VertexElementUsage.Position, 0),
                new VertexElement(12, VertexElementFormat.Vector2, VertexElementUsage.TextureCoordinate, 0),
                new VertexElement(20, VertexElementFormat.Vector2, VertexElementUsage.TextureCoordinate, 1)
            );

            VertexDeclaration IVertexType.VertexDeclaration { get { return dec; } }
        }


        VertexDualTexture[] quad = new[] {
            new VertexDualTexture() { Position = new Vector3(120, 120 + 256, 0), TextureCoordinate = new Vector2(0, 1), TextureCoordinate2 = new Vector2(0, 1) },
            new VertexDualTexture() { Position = new Vector3(120, 120, 0), TextureCoordinate = new Vector2(0, 0), TextureCoordinate2 = new Vector2(0, 0) },
            new VertexDualTexture() { Position = new Vector3(120 + 256, 120 + 256, 0), TextureCoordinate = new Vector2(1, 1), TextureCoordinate2 = new Vector2(1, 1) },
            new VertexDualTexture() { Position = new Vector3(120 + 256, 120, 0), TextureCoordinate = new Vector2(1, 0), TextureCoordinate2 = new Vector2(1, 0) }
        };

        public Game1()
            : base() {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }

        /// <summary>
        /// Allows the game to perform any initialization it needs to before starting to run.
        /// This is where it can query for any required services and load any non-graphic
        /// related content.  Calling base.Initialize will enumerate through any components
        /// and initialize them as well.
        /// </summary>
        protected override void Initialize() {
            // TODO: Add your initialization logic here

            base.Initialize();
        }

        /// <summary>
        /// LoadContent will be called once per game and is the place to load
        /// all of your content.
        /// </summary>
        protected override void LoadContent() {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new SpriteBatch(GraphicsDevice);

            // TODO: use this.Content to load your game content here
            texture_0 = Content.Load<Texture2D>(@"mono");
            texture_1 = Content.Load<Texture2D>(@"sketch");

            dt_effect = new DualTextureEffect(GraphicsDevice) {
                Texture = texture_0,
                Texture2 = texture_1,
                FogEnabled = false,
                VertexColorEnabled = false
            };


            v_buffer = new VertexBuffer(GraphicsDevice, typeof(VertexDualTexture), 4, BufferUsage.None);
            rt = new RenderTarget2D(GraphicsDevice, 20, 20);
        }

        /// <summary>
        /// UnloadContent will be called once per game and is the place to unload
        /// all content.
        /// </summary>
        protected override void UnloadContent() {
            // TODO: Unload any non ContentManager content here
        }

        /// <summary>
        /// Allows the game to run logic such as updating the world,
        /// checking for collisions, gathering input, and playing audio.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Update(GameTime gameTime) {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            // TODO: Add your update logic here

            base.Update(gameTime);
        }

        /// <summary>
        /// This is called when the game should draw itself.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Draw(GameTime gameTime) {

            GraphicsDevice.SetRenderTarget(rt);

            GraphicsDevice.SetRenderTarget(null);
            GraphicsDevice.Clear(Color.CornflowerBlue);

            var viewport = GraphicsDevice.Viewport;
            Matrix projection = Matrix.CreateOrthographicOffCenter(0, viewport.Width, viewport.Height, 0, 0, 1);
            Matrix halfPixelOffset = Matrix.CreateTranslation(-0.5f, -0.5f, 0);


            v_buffer.SetData<VertexDualTexture>(quad);
            GraphicsDevice.SetVertexBuffer(v_buffer);
            GraphicsDevice.BlendState = BlendState.AlphaBlend;

            dt_effect.World = Matrix.Identity;
            dt_effect.View = Matrix.Identity;
            dt_effect.Projection = halfPixelOffset * projection;

            foreach (var pass in dt_effect.CurrentTechnique.Passes) {
                pass.Apply();
                GraphicsDevice.DrawPrimitives(PrimitiveType.TriangleStrip, 0, 12);
            }

            base.Draw(gameTime);
        }
    }
}
```

The expected result would be:
![expected_1](https://cloud.githubusercontent.com/assets/9132168/7014151/f9830250-dcb8-11e4-844f-cbead1a406c2.png)

Instead I'm getting an blue window, running this example on WinGL yields the expected results. Removing the rentertarget swap or adding also "fixes" the problem:
```C#
GraphicsDevice.Textures[1] = null;
```

**Comment by mrhelmut** [comment]
I stumbled upon your forum post, and I can confirm that ```GraphicsDevice.Textures[1] = null; // or whatever, even non-null``` needs to be called so that the sampler texture is correctly set upon a draw call.

I am going to have a look at this.

**Comment by tomspilman** [comment]
@tgjones - This seems possibly related to https://github.com/mono/MonoGame/pull/3554.

**Comment by tgjones** [comment]
I'm pretty sure it's related. I haven't investigated yet - but hopefully it's easy to extend Texture2DTest with a new, initially failing, test.

**Comment by mrhelmut** [comment]
The problem seems to be that the samplers' texture are being reset when swapping render targets, but the ```TextureCollection``` is not cleared, so when ```Effect.ApplyPass``` tries to set the texture parameter, ```TextureCollection``` assume it to be already set from the previous frame and does not properly set the ```TextureCollection._dirty``` flag so that ```TextureCollection.PlatformSetTextures()``` knows which textures to set.

**Comment by tgjones** [comment]
Ah, interesting. In which case this bug (probably) isn't related to #3554.

**Comment by mrhelmut** [comment]
I think so too.

I think that the problem is related to this condition: https://github.com/mono/MonoGame/blob/d752549e9aee29e8cc59aa0fa26fdffbfa1aa980/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs#L33

It assumes that everything within ```_textures``` is a RenderTarget, but if it is a non-null Texture (such as an effect parameter) it is skipped while it should be set to null.

Would it be safe to do this?

```
                if (_textures[i] is RenderTarget2D &&
                    _textures[i] != target0 &&
                    _textures[i] != target1 &&
                    _textures[i] != target2 &&
                    _textures[i] != target3)
                    continue;
```

**Comment by tomspilman** [comment]
> It assumes that everything within `_textures` is a RenderTarget

That is explicitly the intent of that code.  It is trying to clear any active render targets from the texture collection.

> but if it is a non-null Texture (such as an effect parameter) it 
> is skipped while it should be set to null.

That does not sound correct to me.  This isn't about clearing all textures.... it is about not allowing you to write and read from a render target at the same time.

**Comment by tomspilman** [comment]
So still not sure of the issue here.

I did notice we're probably doing too much work in that loop.  We should probably add:

```
            for (var i = 0; i < _textures.Length; i++)
            {
                if (_textures[i] == null) // ADD ME!
                   continue;

                if (_textures[i] != target0 &&
                    _textures[i] != target1 &&
                    _textures[i] != target2 &&
                    _textures[i] != target3)
                    continue;
```
Currently it is doing extra comparisons, the mask clearing, the `_texture[]` clear, and setting GPU state via `SetShaderResource` when the texture slot is null and nothing needs to happen.

Still don't think that is any sort of fix here.

**Comment by mrhelmut** [comment]
My bad!

Is there a way to know when a ShaderResource is changed? I'm still trying to figure out when the sampler textures are set to null by the device.

**Comment by tomspilman** [comment]
> Is there a way to know when a ShaderResource is changed?

The only thing that should change it is MonoGame code itself.  So just look at the places it is referenced... should be only 2 places that I know of.

**Comment by mrhelmut** [comment]
Sure, it is only set in ```TextureCollection.PlatformSetTextures()```, but what's puzzling me is that somewhere, the device loses the resource but the TextureCollection is not made aware of it. Problem is that it seems to happen outside of MonoGame and I don't know how to track where that sampler resource gets reset.

**Comment by pfferrao** [comment]
Hi again,

I found the commit that introduced this bug:
d752549e9aee29e8cc59aa0fa26fdffbfa1aa980

Reverting it fixes this bug: 
```
git revert d752549e9aee29e8cc59aa0fa26fdffbfa1aa980
```
I will look in to the modifications to if I can fix them

Thanks for the help

**Comment by tgjones** [comment]
@pfferrao Thanks for looking at this. I've looked at the code again, and I can't see anything obviously wrong. It will be interesting to see how you get on.

**Comment by pfferrao** [comment]
I've found the problem, is in the internal ClearTargets of MonoGame.Framework/Graphics/TextureCollection.DirectX.cs. The following patch should fix it:
```
diff --git a/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs b/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs
index 8797327..0aa83ce 100644
--- a/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs
+++ b/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs
@@ -12,8 +12,11 @@ namespace Microsoft.Xna.Framework.Graphics
 
         internal void ClearTargets(GraphicsDevice device, RenderTargetBinding[] targets)
         {
-            ClearTargets(targets, device._d3dContext.VertexShader);
-            ClearTargets(targets, device._d3dContext.PixelShader);
+            if (_applyToVertexStage) {
+                ClearTargets(targets, device._d3dContext.VertexShader);
+            } else {
+                ClearTargets(targets, device._d3dContext.PixelShader);
+            }
         }
 
         private void ClearTargets(RenderTargetBinding[] targets, SharpDX.Direct3D11.CommonShaderStage shaderStage)
```

**Comment by tomspilman** [comment]
@pfferrao - That is a bug...  it was clearing things twice as much as it needed too.  Still don't see how that could cause textures that should be bound to not be bound.

**Comment by mrhelmut** [comment]
Made a PR out of your findings.

I can confirm it fixes the issue. It was hard to track why, but the redundant clearings had side effects on PlatformSetTextures.

**Comment by tomspilman** [comment]
Cool!  Thanks @mrhelmut !

**Comment by tgjones** [comment]
Thanks @mrhelmut and @pfferrao!
