### ISSUE TITLE
Need to build Android openal-soft for new 64bit Architectures

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#3899]
Android now has a few of new architectures. x86_64, arm64-v8a to name two. 
We need to recompile the Native libraries for these new platforms.
It might also be handy to document how to do this, so that perhaps we can integrate it somehow into the build system so it doesn't have to be done manually in the future.

**Comment by dellis1972** [comment]
@KonajuGames thoughts? :)

**Comment by KonajuGames** [comment]
The two .mk files here
https://github.com/Mono-Game/openal-soft/tree/master/build/android/jni
control which architectures are built and how.  It might also be worth dropping `armeabi` as it will no longer be used.  Maybe updating the NDK_TOOLCHAIN_VERSION in `Application.mk` as well.  Then it is simply a case of running ndkbuild.

As for 64-bit compatibility, I cannot guarantee this version of openal-soft will work.

**Comment by KonajuGames** [comment]
And we have no way of testing these architectures yet.

**Comment by KonajuGames** [comment]
It would also be nice to update to the latest openal-soft to get the Android fix for suspending the mixer thread while the app is in the background.  The fix is only in the official repo, which has no Android make files.  The forks of openal-soft for Android that I know of are way out of date.

**Comment by danzel** [comment]
In relation to the CPU usage, I just found:
https://github.com/AerialX/openal-soft-android/issues/4

And a PR for building for android (useful as notes)
https://github.com/kcat/openal-soft/pull/5/files
We could probably tidy up the PR, use the makefiles and re-submit the change to the original repo?

**Comment by KonajuGames** [comment]
I have a fully managed audio resampler and mixer running on Android.  No more native library mess.  It does not yet have support for 3D or ADPCM.  If we could live without those features, it should be almost ready for a PR.  Then we have support for all architectures that Xamarin.Android supports.

**Comment by danzel** [comment]
If you have a monogame branch I'll happily make use of it for now and give some early testing.
I'm only using Song and basic audio.

**Comment by KonajuGames** [comment]
I'll push a branch up tonight.

**Comment by danzel** [comment]
<3

**Comment by KonajuGames** [comment]
https://github.com/KonajuGames/MonoGame
in the `managed-mixer` branch.  I'm keen to hear how you go with it.

**Comment by danzel** [comment]
Awesome, will plug it in in the next few days

**Comment by mrhelmut** [comment]
Oh, if I have some spare time, I'll gladly test this mixer. Pretty interesting work.

**Comment by danzel** [comment]
I cherry picked the commit in to my oldish branch, so some of my issues may come from that. Will work on getting updated to retest.

Things I found:
- Sounds play noticeably delayed compared to the old system.
- Sometimes sounds would play at random pitches. I have one sound that should always play at the same pitch, and others that vary. The one that always plays at the same pitch was randomly playing at a varied pitch.
- Sometimes sounds wouldn't play, may be related to the random pitches.

**Comment by KonajuGames** [comment]
> Sounds play noticeably delayed compared to the old system.

It is using the device's native sample rate and buffer size in order to enable the low latency audio path.  But I'll definitely have a look at this.

> Sometimes sounds would play at random pitches. I have one sound that should always play at the same pitch, and others that vary. The one that always plays at the same pitch was randomly playing at a varied pitch.

That's odd.  I never saw that.  Do you have some sample code that shows how you are playing the sounds?

> Sometimes sounds wouldn't play, may be related to the random pitches.

Are those sounds compressed as ADPCM?  They're not supported yet.

**Comment by KonajuGames** [comment]
I pushed a commit to the branch that should reduce the latency of audio playback.  I haven't been able to get any repro with random pitches.

**Comment by dellis1972** [comment]
Hey @KonajuGames could we finally implement a DynamicSoundEffectInstance
with any of this?

**Comment by KonajuGames** [comment]
It will be a lot easier, because the mixer itself is basically a DynamicSoundEffectInstance already.

**Comment by dellis1972** [comment]
cool.

On a side note, it would be good to test this on older devices. I have some
old ones if someone wants to knock up a sample .apk I can give it a go.

**Comment by KonajuGames** [comment]
I tested on a Nexus S tonight.  That is the oldest device I have.  Also tested on a SHIELD handheld.

**Comment by dellis1972** [comment]
I have a Galaxy S 1 ... if it works on that it will work on almost anything
:)

**Comment by danzel** [comment]
Thanks, will bring the update in to my local branch and see if I can make a pitch repro at the weekend.

**Comment by danzel** [comment]
Ok, retested with the updated branch, still some random pitch changes and the audio is still noticeably delayed.
Going to work on a repro project now.

**Comment by danzel** [comment]
Ok, here is a nice easy repro:
https://github.com/danzel/WrapTest/tree/android-managed-mixer-test

Run it, tap the bottom of the screen a few times, you'll hear a tone with fixed pitch.
Tap the top a few times, we play another sound, but with (desired) random pitch.

Now tap the bottom, each time the tone will play with random pitch!

Relevant section of code:
https://github.com/danzel/WrapTest/blob/android-managed-mixer-test/WrapTest/WrapTest/Game1.cs#L81-L92

**Comment by KonajuGames** [comment]
Thanks for that @danzel. I fixed the random pitch (wasn't resetting the pitch, pan or volume when grabbing an instance from the pool).

The delay in playing...   what device and version of Android are you testing on?  I tested on
- VS Emulator for Android. No delay.
- Samsung Nexus S (Android 4.1.2). Small delay.  To be expected from old hardware.
- SHIELD handheld (Android 5.1). Smaller delay than the Nexus S, but still a slight delay though in most cases it wouldn't be a real problem.

I measured this delay by using a sound effect that had no silence at the start and displaying a white square on screen at the same time I played the sound.

The mixer will try to use the low latency path where possible.  Later versions of Android help in this by making the native buffer size and sample rate available to the app.  Earlier versions need the app to make a best guess but will usually result in the system doing a rebuffer or resample which adds to the latency in hearing the sound.

**Comment by danzel** [comment]
I'm using a Moto G LTE on Android 4.4.4, testing using the WrapTest example above.
Have updated the example to flash the screen red when the sound starts to play.

Slowmo video, audio is a bit quiet and low pitch.

Existing mixer:
https://www.youtube.com/watch?v=dQHn18nswLU
Managed mixer:
https://www.youtube.com/watch?v=3y-7ng2-mM8

The managed mixer is delayed around an extra 125-200ms delay (1-1.5s in the slowmo video)

**Comment by KonajuGames** [comment]
@danzel, I just pushed a small change that made a great improvement on my Samsung Nexus S.  It now defaults to a smaller buffer when the native buffer size cannot be retrieved.

**Comment by danzel** [comment]
Awesome, will hopefully check it out tonight.

**Comment by danzel** [comment]
Sadly that didn't change anything, my device returns 1920 for ```AudioManager.PropertyOutputFramesPerBuffer```, which sets this variable anyway.
If I comment that out and use the default value you've set now the delay is still the same (Worse than the existing mixer).

In the logs I get:
Does not support low latency audio playback.
Mixer starting with buffer of 1920 stereo samples. Native sample rate 44100

**Comment by KonajuGames** [comment]
Unfortunately the wide variance in Android hardware and the low priority placed on low latency audio by most manufacturers results in a wide discrepancy of results.  It is frustrating for all aspects of Android development, and obtaining the hardware to test all these cases isn't feasible.  Xamarin's cloud testing can only do so much.

I have made another push to the branch to try setting the mixer thread to URGENT_AUDIO priority.  Not sure if it will have much effect, but I'm hoping.
