### ISSUE TITLE
Microsoft.Xna.Framework.Vector2 serializes incorrectly

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3981]
This seems to be a regression of https://github.com/mono/MonoGame/issues/2968, however with one slight caveat: the serialization now differs by platform.

Currently, with the 3.4 release version of Monogame, the following output occurs during serialization with Json.NET (for `foo.Position = new Vector2(-60, -60)`).

Windows: 
```"Position" : "-60, -60"```
Linux: 
```"Position": {
    "X": -60.0,
    "Y": -60.0
}```

The reason that we noticed this is because the Windows serialization does not correctly deserialize on Linux as would be expected. We have not yet tried to deserialize the Linux version on Windows.

**Comment by WardBenjamin** [comment]
So, I just tried using the Linux serialization on Windows, here's the error:

```Additional information: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Microsoft.Xna.Framework.Vector2' because the type requires a JSON string value to deserialize correctly.```

**Comment by tomspilman** [comment]
The problem is that this was never fixed for non-Windows platforms:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs#L15

I suspect if we remove the `#if WINDOWS` from the attribute things would work correctly.  Can you check this @WardBenjamin ?

**Comment by WardBenjamin** [comment]
Yeah I can. I'll report back in a moment.

Relating to this, I just noticed that the serialization works correctly for Rectangles, using attributes as expected.

**Comment by WardBenjamin** [comment]
I'm currently also having some other (unrelated) issues with an error on content loading, I'll get back to this when those are resolved (probably tomorrow).

**Comment by BajtCZ** [comment]
Was the bug fixed in newer builds?

I have this problem in MonoGame 3.4 but in 3.1 it works great.

**Comment by cra0zy** [comment]
Fixed in #4614

**Comment by cra0zy** [comment]
The PR is not yet merged so this should maybe still stay open?

**Comment by Mathetis** [comment]
This is still happening in Monogame 3.6 on Android and Windows.

Error converting value \"0, 0\" to type 'Microsoft.Xna.Framework.Vector2'.
