### ISSUE TITLE
BasicEffect / Model processor Lighting issues

### ISSUE THREAD

**Issue by nilllzz** [mono/MonoGame#4069]
Hello there,

I encountered a few issues with the lighting features of the BasicEffect and its relation to the Model Processor of MonoGame.
  1. The BasicEffect lighting does not seem to apply correct (tested with the EnableDefaultLighting), it just casts the same light on all parts of the model, ignorning direction. This might be directly related to 
  2. The Model Processor seems to somehow mess up normals of the model (or something else related to lighting, I am not sure). This causes light applied by the BasicEffect to look the same for the entire model and appear black.

I have an illustration of this occurence here, compared to XNA's output:
![wxpsjlt](https://cloud.githubusercontent.com/assets/2119926/9210458/b9a0efe4-407c-11e5-82c2-47c3adb501ec.png)

(Also, on that note, GraphicsDeviceManager.PreferMultiSampling does not seem to prefer multi sampling, it is activated on all models on those screenshots above, but does not seem to apply in MonoGame [yes, GraphicsDeviceManager.ApplyChanges() has been called]).

**Comment by InfiniteProductions** [comment]
I have a similar issue, a model from a FBX 2014 ascii file, exported from 3DSMax 2015 works fine with XNA. same model, same code, MonoGame only render a full black model, with LightingEnabled set to true or false. Also tried with the today dev snapshot of MG, same result.

I'll add test code later.

**Comment by mgarstenauer** [comment]
@InfiniteProductions I did a quick test and everything is working here. (My dev snapshot is from December.)

I see that you are referencing `H:\MonoGame-dev\Windows\AnyCPU\Debug\MonoGame.Framework.dll` in your `FBXMP-MGdev_dn45.csproj`. But the Content.mgcb is built using the standard MSBuild task `$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets`.

Perhaps you are using the dev snapshot at runtime, but the content project is compiled using the old binaries in `C:\Program Files (x86)\MSBuild\MonoGame\v3.0`?

**Comment by nilllzz** [comment]
According to the pull, it was resolved in November, so using your December build of MonoGame, it might just work because it got fixed.

**Comment by InfiniteProductions** [comment]
@mgarstenauer : doohhh!  Is it a common issue or something specific to using two, or more, sets of MG on the same computer ? (I have a stable install, 3.x, x=4 maybe) + the dev snapshot and I wasn't aware at all of this use of MSBuild path.

It's off-topic sorry, is there any (simple) way to fix that ?
Thanks.

**Comment by InfiniteProductions** [comment]
Anyone ?
$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets doesn't exists, but VS 2013 Ex is happy with that, changing the path with another, and still not existing "MonoGame.Content.Builder.targets" in it doesn't make it works :/.

**Comment by KonajuGames** [comment]
The file in that path is installed by the MonoGame Windows installer.

**Comment by InfiniteProductions** [comment]
Little update: issue is good to be closed now, tested with one of my project using a dev snapshot from 05/29/16, lighting works (don't forget to add some light ;) )
