### ISSUE TITLE
VS2015 MonoGame compiling problem

### ISSUE THREAD

**Issue by Chaosus** [mono/MonoGame#4118]
I cannot compile MonoGame inside visual studio 2015. I dont know how to fix it. 

![image](https://cloud.githubusercontent.com/assets/3036176/9623411/9c28fa56-5148-11e5-813a-2211c7ec4bcb.png)

The other IDE's like xamarin studio or sharpdevelop are not affected by this problem.

**Comment by danzel** [comment]
Have you installed .net 4?
If you've just done a new PC install you might not have it maybe? :S
(Just guessing)

**Comment by KonajuGames** [comment]
That's a problem I've had as well.  Couldn't find a solution.  I ended up installing VS2013 and using that again.

**Comment by tomspilman** [comment]
Note there are also issues with the new NuGet which will read the config meant for Win10 builds and apply it to the Windows desktop or Windows 8 builds.

IMO don't bother using VS2015 for anything other than Win10 builds for now.  There are still a lot of issues that are being worked out.

**Comment by BrianPeek** [comment]
Either use VS2013 or delete the project.json file in the MonoGame.Framework directory.

**Comment by Shqrdx** [comment]
@danzel The problem is in .json file.
@BrianPeek @tomspilman Why not change this file(or remove it) and everything will be ok ?

**Comment by BrianPeek** [comment]
It is required for building the Windows 10 UWP version of MonoGame.

**Comment by Shqrdx** [comment]
Then include it only for Windows 10 UWP project.

**Comment by BrianPeek** [comment]
Unfortunately VS2015 references and tries to use the file even in non-Win10 UWP builds.  It is a known issues and there is no known workaround at present other than restructuring the entire project/build setup of MonoGame which is not possible.  For now, the options are to build with VS2013 or simply delete the file if using VS2015 and NOT building the UWP project.

**Comment by BrianPeek** [comment]
More info here:  https://github.com/NuGet/Home/issues/1102

**Comment by kjpou1** [comment]
Ran into this obscure problem with only Visual Studio 2015 installed on Windows 10 - https://social.msdn.microsoft.com/Forums/sqlserver/en-US/8cb70b42-c45c-4d2c-989c-6affa2a88343/w81netcore-error-message-when-building-win81-app-on-win10?forum=wpdevelop which prevented any of the MonoGame projects to build on Visual Studio 2015.  Even deleting the lock file it still showed the same problems.  Thus ensued more uninstalls of VS and finally an install of VS 2013 community edition which still did not help.  Turns out that you can not just do a repair or anything you have to un-install VS 2015 completely AND REBOOT the windows 10 then install VS 2015 from scratch WITH VS 2013 community edition ALREADY installed.  Make sure the project.lock.json file is deleted and once all this dancing is done it looks like MG projects are able to be compiled and run.

This is also why I created the PR https://github.com/mono/MonoGame/pull/4092

**Comment by hach-que** [comment]
Yeah, you can't use `project.json` files in cross-platform projects because Visual Studio will use them instead of the `.csproj` file.  Instead you need to delete the `project.json` file and just use the generated `.csproj` for that target platform.

(Again `project.json` uses NuGet for dependencies, which doesn't have proper platform-specific support)

**Comment by hach-que** [comment]
(One alternative here is to pull in NuGet packages via Protobuild directly, using the `https-nuget://www.nuget.org/api/v2|PackageName@Version` URL format; see http://protobuild.readthedocs.org/en/latest/package_management_nuget.html)

**Comment by tomspilman** [comment]
Actually this is now fixed if you install WinTools 1.1...

> - Added support for multiple csproj in one folder with project.json, with {projectName}.project.json support.

https://social.msdn.microsoft.com/Forums/en-US/e9df01f6-1474-4a4e-98fc-2567591c764f/update-11-release-notes-and-installation-instructions?forum=Win10SDKToolsIssues

No clue how long before this is all just part of VS2015 out of the box.

**Comment by hach-que** [comment]
The issue still occurred in Visual Studio Code last I checked (about a month ago).

**Comment by BrianPeek** [comment]
Fix is sitting in PR #4163 (assuming you install WinTools 1.1 with VS2015).  Not sure what the situation is with VS Code, however.

**Comment by BrianPeek** [comment]
@tomspilman VS2015 add-ons are "automatic".  The items are pulled from a live feed at install time, so the latest is what's downloaded/installed.  If you install VS2015 today and select the UWP tools option, you get v1.1 which contains the fixes.

**Comment by tomspilman** [comment]
> VS2015 add-ons are "automatic". 

Ah... so everyone should have it that installed VS2015 in the last few weeks.

I guess for older installs of VS those people have a notification in the IDE to install the latest tools.

So it should be a minor disruption for VS2015 users.

**Comment by BrianPeek** [comment]
Yes, anyone that installed since v1.1 was released will have it if they installed the UWP tools.  And, those that didn't *should* get a notification.  If not, they can install by going to Add/Remove Programs and hitting Modify on the VS2015 entry.  Any/all items in the feed that are updated since the last install will show up in the list and can be installed.

**Comment by kjpou1** [comment]
Hey guys could someone look at this pull request:  https://github.com/mono/MonoGame/pull/4203

**Comment by kjpou1** [comment]
Oh I just noticed that Brian already has an open PR for this.  Could someone then look at the PR 4163 and I will close out mine.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed in #4163
