### ISSUE TITLE
"OpenAL drivers could not be found" on Windows 10

### ISSUE THREAD

**Issue by ChlorideCull** [mono/MonoGame#4329]
It seems the installer fails to run - any attempts to play sound gives the aforementioned exception. It got fixed after I ran the OpenAL installer from openal.org, so I believe the bundled version might fail to run.

**Comment by mrhelmut** [comment]
I can confirm that it also fails on Windows 8.1. Despite checking OpenAL in the installer (develop branch), everything seems normal but it isn't installed.

**Comment by tomspilman** [comment]
Could be we just need to update to a newer version of the OpenAL installer that deals with changes in the new OSs.  I don't think we've changed that installer for 4 or 5 years now.

**Comment by KonajuGames** [comment]
I don't think there is a new version of the installer. Creative Labs
stopped distributing it several years back.  OpenAL Soft is a recommended
drop in replacement that doesn't need installation. It's just a DLL to use.

**Comment by tomspilman** [comment]
Yeah... There is really zero benifit to hardware accelerated sound on desktops.  I wouldn't have a problem with moving desktop builds towards a software OpenAL implementation.

**Comment by mrhelmut** [comment]
Yes, the latest OpenAL Soft pre-compiled DLL works just great and its license allows to ship it with a game.

**Comment by tomspilman** [comment]
So could we maybe include the software OpenAL dll as part of the Desktop template projects?  This way it is just there and should work without any need to install any OpenAL stuff.

**Comment by KonajuGames** [comment]
That would work well, just like any other binary dependency we use.​

**Comment by Jjagg** [comment]
Fixed by #4874.

**Comment by kingq8y** [comment]
Fix the 
https://www.openal.org/downloads/

**Comment by sweep3r** [comment]
Still an issue, win 10, MG 3.8.0.848, install from .org download has fixed it.

**Comment by Jjagg** [comment]
@sweep3r MonoGame includes openal-soft - a software implementation of OpenAL - so you don't need to have it installed anymore. The library probably was not copied over correctly for you, but I can't help without more information.

**Comment by mrhelmut** [comment]
Also: it is absolutely not advisable to use the dll/installer from openal.org. It is an unofficial website about a discontinued version of the library. Bugs and incompatibilities are likely to show up if used.

The way to go is the official openal-soft website and binaries: https://openal-soft.org/

MonoGame doesn't require OpenAL to be installed at all. It ships with its own up-to-date runtime.

If you have issues with OpenAL not being found, please make sure that you are using the proper project template and that your project is packaged correctly.
